version: '3.9'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
      target: backend
    volumes:
      - ./src:/usr/src
    ports:
      - 8080:80
    container_name: backend
    tty: true