version: '3.9'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
      target: backend
    volumes:
      - ./backend:/usr/src
      - ./.secret:/.secret
    ports:
      - 8080:80
    env_file:
      - backend.env
    container_name: backend
    tty: true
  

  postgres:
    container_name: postgres_con
    # build: ./image/postgres
    image: postgres:15
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    env_file:
      - db.env

