version: '3.9'

services:
    python3:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - type: bind
              source: ./src
              target: /usr/src
        ports:
            - 8080:80
        container_name: python3.11
        tty: true
