version: '3.9'

services:
    backend:
        build:
            context: ./
            dockerfile: Dockerfile
            target: backend
        volumes:
            - type: bind
              source: ./src
              target: /usr/src
        ports:
            - 8080:80
        container_name: backend
        tty: true
